# Database
spring.datasource.url: jdbc:mysql://localhost:3306/fairanb_customer?createDatabaseIfNotExist=true&useSSL=false&zeroDateTimeBehavior=convertToNull
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.show-sql: true
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: MYSQL
spring.datasource.platform: mysql
spring.jpa.hibernate.ddl-auto: validate

# flyway 
flyway:
    baselineOnMigrate: true
    
# Spring Cloud
spring:
  mail: 
    host: email-smtp.us-east-1.amazonaws.com 
    port: 465 
    username: ArknRQx****** 
    password: ArknRQx****** 
    protocol: smtps 
    debug: true 
    properties.mail.smtp: 
      starttls.enable: true 
      starttls.required: true 
      ssl.enable: true 
    properties.mail.smtps: 
      auth: true
  cloud:
    stream:
      bindings:
        output:
            destination:  customerChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost    
# Cloud  
cloud:
  aws:
    credentials:
      accessKey: ArknRQx******
      secretKey: ArknRQx******
    region:
      static: us-east-1       
                  
# Gateway Zuul Feign
gateway.server: http://localhost:5555

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# Setting the logging levels for the service
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.fairanb: DEBUG     
  

