# Database
spring.datasource.url: jdbc:mysql://fairanbv2.cjdoyiqgd23g.us-east-1.rds.amazonaws.com:3306/fairanb_customer?createDatabaseIfNotExist=true&useSSL=false&zeroDateTimeBehavior=convertToNull
spring.datasource.username: userdb
spring.datasource.password: Pass!234
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.show-sql: true
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: MYSQL
spring.datasource.platform: mysql
spring.jpa.hibernate.ddl-auto: validate

# Flyway 
flyway:
    baselineOnMigrate: true
    
# Spring Cloud
spring:
  mail: 
    host: email-smtp.us-east-1.amazonaws.com 
    port: 465 
    username: ArknRQx****** 
    password: ArknRQx****** 
    protocol: smtps 
    debug: true 
    properties.mail.smtp: 
      starttls.enable: true 
      starttls.required: true 
      ssl.enable: true 
    properties.mail.smtps: 
      auth: true
  cloud:
    stream:
      bindings:
        output:
            destination:  customerChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: kafka-server
            brokers: kafka-server    
# AWS  
cloud:
  aws:
    credentials:
      accessKey: ArknRQx******
      secretKey: ArknRQx******
    region:
      static: us-east-1       
                  
# Gateway Zuul Feign
gateway.server: http://gateway-service:5555

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
      
# Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG