# Database
spring.datasource.url: jdbc:mysql://fairanbv2.cjdoyiqgd23g.us-east-1.rds.amazonaws.com:3306/fairanb_merchant?createDatabaseIfNotExist=true&useSSL=false&zeroDateTimeBehavior=convertToNull
spring.datasource.username: userdb
spring.datasource.password: Pass!234
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.show-sql: true
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: MYSQL
spring.datasource.platform: mysql
spring.jpa.hibernate.ddl-auto: validate

# flyway 
flyway:
    baselineOnMigrate: true
    
# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
        
# Spring 
spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  merchantChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: kafka-server
            brokers: kafka-server    

# Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG             